PROJECT_DIR = ./../../

# Points to the root of fused Google Test, relative to where this file is.
GTEST_DIR = googletest-release-1.10.0/googletest

# Paths to the fused gtest files.
GTEST_H = $(GTEST_DIR)/include/gtest/gtest.h
GTEST_ALL_CC = $(GTEST_DIR)/src/gtest-all.cc
GTEST_MAIN_CC = $(GTEST_DIR)/src/gtest_main.cc

all: unit_tests

subsystem: $(MAKE) -C $(PROJECT_DIR)