name: Unit tests - Clang Linux

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout the project
      uses: actions/checkout@v2
    - name: CMake
      run: |
        mkdir build
        cd ./build
        CC=/usr/bin/clang-18 CXX=/usr/bin/clang++-18 cmake -G"Unix Makefiles" ./.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: Make
      run: |
        cd ./build
        make
    - name: Clang-Format
      run: |
        find ./src ./tests ./include \
          -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.tpp" \) \
          ! -path "./src/external_library/*" \
          -exec clang-format --dry-run --Werror --verbose \
          {} +
    - name: Clang-Tidy
      run: |
        find ./src ./tests ./include \
          -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.tpp" \) \
          ! -path "./src/external_library/*" \
          -exec clang-tidy -p .\build\ -header-filter=.* \
          {} +
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiled-tests
        path: build/tests/

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: compiled-tests
        path: ./build/tests/
    - name: Run tests
      run: |
        chmod -R +x ./build/tests/
        ./build/tests/unit_tests/UnitTests --gtest_also_run_disabled_tests
