name: Dataset tests Linux

push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: CMake
      run: |
        mkdir build
        cd ./build
        cmake -G"Unix Makefiles" ./..
    - name: make
      run: |
        cd ./build
        make
    -name: download datasets
      run: |
        cd ./build
        ./ImportDatasets.sh
    - name: Iris
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests.out --gtest_filter=IrisTest
    - name: Wine
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests.out --gtest_filter=WineTest
    - name: MNIST
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests.out --gtest_filter=MnistTest
    - name: CIFAR-10
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests.out --gtest_filter=Cifar10Test
        