name: Dataset tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Build and run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout projet
      uses: actions/checkout@v2
    - name: Checkout datasets
      uses: actions/checkout@v2
      with:
        repository: MatthieuHernandez/Datasets-for-Machine-Learning
        path: ./build/datasets
    - name: CMake
      run: |
        cd ./build
        cmake -G"Unix Makefiles" ./..
    - name: make
      run: |
        cd ./build
        make
    - name: Iris
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests --gtest_filter=IrisTest* --gtest_also_run_disabled_tests
    - name: Wine
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests --gtest_filter=WineTest* --gtest_also_run_disabled_tests
    - name: DailyMinTemperatures
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests --gtest_filter=DailyMinTemperaturesTest* --gtest_also_run_disabled_tests
    - name: MNIST
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests --gtest_filter=MnistTest* --gtest_also_run_disabled_tests
    - name: Fashion MNIST
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests --gtest_filter=FashionMnistTest* --gtest_also_run_disabled_tests
    - name: CIFAR-10
      run: |
        cd ./build
        ./tests/dataset_tests/DatasetTests --gtest_filter=Cifar10Test* --gtest_also_run_disabled_tests
        