name: Unit tests Clang Linux

on: [push]

jobs:
  unit-tests:
    name: Build and run
    runs-on: ubuntu-latest

    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 19
        platform: x64
    - name: Checkout the project
      uses: actions/checkout@v2
    - name: CMake
      run: |
        cd ./build
        CXX=/usr/bin/clang-19 cmake -G"Unix Makefiles" ./.. -DCMAKE_BUILD_TYPE=Release
    - name: Make
      run: |
        cd ./build
        make
    - name: Execute unit tests
      run: |
        cd ./build
        ./tests/unit_tests/UnitTests --gtest_also_run_disabled_tests